//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssetManagementAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        public decimal pd_id { get; set; }
        public string pd_order_no { get; set; }
        public Nullable<decimal> pd_ad_id { get; set; }
        public Nullable<decimal> pd_type_id { get; set; }
        public Nullable<decimal> pd_qty { get; set; }
        public Nullable<decimal> pd_vendor_id { get; set; }
        public DateTime pd_odate { get; set; }
        public string pd_odateStr
        {
            get
            {
                return pd_odate.ToString("yyyy/MM/dd");
            }
        }
        public Nullable<DateTime> pd_ddate { get; set; }
        public string pd_ddateStr
        {
            get
            {
                return pd_ddate.ToString();
            }
        }
        public string pd_status { get; set; }
    
        public virtual asset_def asset_def { get; set; }
        public virtual asset_type asset_type { get; set; }
        public virtual vendor_creation vendor_creation { get; set; }
    }
}
